const styles = {
    container: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      padding: 16,
      backgroundColor: "white",
    },
    balaoAmarelo: {
      backgroundColor: "#F9C200",
      padding: 25,
      alignItems: "center",
      shadowColor: 'black',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.4,
      shadowRadius: 4,
      elevation: 4,
      width: 370,
      height: 90,
      marginBottom: 10,
      borderRadius: 60,
    },
    cadastroForm: {
      flex: 2,
      alignItems: "center",
    },
    cadastroTitle: {
      fontSize: 24,
      fontWeight: "bold",
    },
    input: {
      width: 370,
      height: 90,
      marginBottom: 20,
      borderRadius: 60,
      paddingHorizontal: 10,
      paddingVertical: 8,
      backgroundColor: '#F9C200',
      shadowColor: 'black',
      shadowOpacity: 0.4, 
      shadowRadius: 2,
      elevation: 4, 
      fontSize: 20,
      fontWeight: "bold",
  },
    cadastrarButton: {
      backgroundColor: "#F9C200",
      borderRadius: 60,
      width: 300,
      height: 70,
      alignItems: "center",
      shadowColor: "black",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.4,
      shadowRadius: 4,
      elevation: 4,
      paddingVertical: 10,
      marginBottom: 50,
      marginTop:30,
    },
    textCadastrar: {
      color: "white",
      textAlign: "center",
      fontSize: 30,
      fontWeight: "bold",
    },
    modalContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0, 0, 0, 0.5)",
    },
    modalContent: {
      width: 300,
      backgroundColor: "white",
      padding: 20,
      borderRadius: 10,
      alignItems: "center",
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: "bold",
      marginBottom: 20,
    },
    okButton: {
      backgroundColor: "#F9C200",
      borderRadius: 10,
      width: 100,
      height: 40,
      alignItems: "center",
      justifyContent: "center",
    },
    okButtonText: {
      color: "white",
      fontSize: 16,
      fontWeight: "bold",
    },
    link: {
      fontSize: 20,
      marginBottom: 33,
  
    },
  
  };

  export default styles;